### ISSUE TITLE
UUID実装の件について(完)

### ISSUE THREAD

**Issue by zhon3112** [zhon3112/Empatia#74]
## 解決したいこと・達成したいものについて
UUIDをMySQLで使用したい。

## 聞きたいこと・アドバイスが欲しいこと
- 聞きたいこと
uuidカラムを作成しプライマリーキーのモジュールを作成してインクルードさせる実装方法の方向性はこれであっているのか？　
MySQLがUUIDに対応しているのか？

- アドバイスが欲しいこと
MySQLを使用したUUIDの実装方法はどのような実装方法があるのか？

## 実装の際に参考にした資料等
[Rails5.2.3+MySQL+Ridgepoleでテーブルの主キーにUUIDを使う](https://qiita.com/ryokkkke/items/eb21a757cc058e8ffdc3)

## 現状のコードの状態がわかるURL(プルリクエスト・リポジトリ等)
[UUIDの実装に関して](https://github.com/zhon3112/Empatia/commit/982ed82f85a7e19d187c6245249279db0848c2d8)
　
以下、作成したファイルとコードです。
- db>migrate>20241117065842_add_uuid_to_users.rb
``` 
class AddUuidToUsers < ActiveRecord::Migration[7.1]
  def change
    add_column :users, :uuid, :string
  end
end
``` 

- db>migrate>20241117072130_add_uuid_posts_rb
``` 
class AddUuidToPosts < ActiveRecord::Migration[7.1]
  def change
    add_column :posts, :uuid, :string
  end
end
``` 

- app>models>concerns>primary_key_uuid_auto_generatable.rb
``` 
module PrimaryKeyUuidAutoGeneratable
  extend ActiveSupport::Concern

  included do
    before_create :generate_uuid
  end

  def generate_uuid
    return if self.id.present?

    self.id = SecureRandom.uuid
  end
end
``` 

- app>models>post.rb
```
class Post < ApplicationRecord
  belongs_to :user
  include PrimaryKeyUuidAutoGeneratable

  validates :content, presence: true, length: { maximum: 140 }

  enum status: { visible: 0, is_public: 1 }

  def make_private
    update(status: :is_public)
  end
end
```

- app>models>user.rb
```
class User < ApplicationRecord
	authenticates_with_sorcery!
	has_many :posts
	include PrimaryKeyUuidAutoGeneratable

	validates :password, length: { minimum: 8 }, if: -> { new_record? || changes[:crypted_password] }
	validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
	validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
	validates :username, presence: true, length: { maximum: 10 }
	validates :email, presence: true, uniqueness: true
end
```

## 現状のコードの状態がわかるURLのどこが関係していると考えているのか
上記のファイルとコードを記事を参考に作成しました。
- マイグレーションファイルの2つについて
作成した理由：uuidカラムがないとuuidを作成・割り振ることができないと考えたため作成しました。
 
- userモデル・postモデルのinclude PrimaryKeyUuidAutoGeneratableについて
参考記事から引用して使用しました。　
作成したprimary_key_uuid_auto_generatable.rbを読み込むために記述しています。

## 検証した結果から分かったこと・考えたこと
Railsコンソールを使用してuserテーブルpostテーブルのuuidカラムがnilであることはエラー前に確認しました。　
MySQLがuuidをプライマリーキーとすることに対応していないため、このエラーが発生してDockerすら立ち上がりません...。
``` 
web-1  | Bundle complete! 16 Gemfile dependencies, 98 gems now installed.
web-1  | Use `bundle info [gemname]` to see where a bundled gem is installed.
web-1  | == 20241117065842 AddUuidToUsers: migrating ===================================
web-1  | -- add_column(:users, :uuid, :string)
web-1  | bin/rails aborted!
web-1  | StandardError: An error has occurred, all later migrations canceled: (StandardError)
web-1  | 
web-1  | Mysql2::Error: Duplicate column name 'uuid'
web-1  | /myapp/db/migrate/20241117065842_add_uuid_to_users.rb:3:in `change'
web-1  | 
web-1  | Caused by:
web-1  | ActiveRecord::StatementInvalid: Mysql2::Error: Duplicate column name 'uuid' (ActiveRecord::StatementInvalid)
web-1  | /myapp/db/migrate/20241117065842_add_uuid_to_users.rb:3:in `change'
web-1  | 
web-1  | Caused by:
web-1  | Mysql2::Error: Duplicate column name 'uuid' (Mysql2::Error)
web-1  | /myapp/db/migrate/20241117065842_add_uuid_to_users.rb:3:in `change'
web-1  | Tasks: TOP => db:prepare
web-1  | (See full trace by running task with --trace)
web-1 exited with code 1
```

**Comment by Tsuchiya2** [comment]
プライマリーキーは他のと同様にIDを使用して、ルーティングの定義時にparamをuuidに指定してあがる方が良いかと思いました。

https://qiita.com/naokit-dev/items/609cd1516d1b42b2e033

他にも記事やドキュメントがあるかと思うので調べてみてください。
